[~] - update ami to amazon linux 2
ulamlabs/rabbitmq-cluster pull request #21
Opened 2019-09-19 11:22 UTC by oreststetsiak

update ami to amazon linux 2

2019-11-15 20:40 UTC, rraub requested changes

2019-11-15 20:40 UTC, rraub commented on main.tf
> +  image_id             = data.aws_ami.amazon-linux-2.id
```suggestion
  image_id             = data.aws_ami_ids.amazon-linux-2.ids[0]
```

2019-11-15 20:40 UTC, rraub commented on main.tf
> +  most_recent = true
```suggestion
```
This isn't an valid attribute, https://www.terraform.io/docs/providers/aws/d/ami_ids.html#sort_ascending is probably what you were thinking of but that defaults to descending which is what we want.

2019-11-21 20:38 UTC, rraub commented
Also this ami broke the `find_hosts.sh` script since the `$HOSTNAME` changed from just `ip-10-2-1-82` to `ip-10-2-1-82.ec2.internal` in the newer Amazon Machine Linux 2.  see: https://github.com/smartrent/terraform-aws-rabbitmq/pull/1 if your interested

2020-05-14 09:13 UTC, krotkiewicz commented
Hey @oreststetsiak, thank you for PR and @rraub for comments. 

Currently we don't have resources to prepare CI pipeline with some basic tests or to do tests manually. If you have some spare time and could help here, let me know.

2020-05-14 09:13 UTC, closed without merging